# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  build-webasm:
    name: WebASM
    runs-on: ubuntu-latest
    steps:
      - 
       name: Checkout
       uses: actions/checkout@v2
      - 
       name: Build
       run: | 
         docker build -t plutoboy -f build/WebAsm/Dockerfile .
         docker run -v $(pwd):/mnt plutoboy
